#!/usr/bin/ash

run_hook() {
  if [ "${overlayroot}" ]; then
    mkdir -p /overlay
    if [ "${overlayroot}" = "tmpfs" ]; then
      mount -t tmpfs overlayroot /overlay
    else
      # Allow up to 5 seconds for device to be available
      mounted=0
      for i in 1 2 3 4 5; do
        mount ${overlayroot} /overlay
        [ $? -eq 0 ] && mounted=1 && break
        sleep 1
      done
      # Otherwise mount tmpfs anyway
      [ $mounted -eq 1 ] || mount -t tmpfs overlayroot /overlay
    fi
    mkdir -p /overlay/upper
    mkdir -p /overlay/work
    mkdir -p /overlay/lower

    # Remove /new_root directory and replace it with symlink
    # After run_hook, mount_handler will mount our rootfs into here /new_root
    rmdir /new_root
    ln -s /overlay/lower /new_root
  fi;
}

run_latehook() {
  if [ "${overlayroot}" ]; then
    # Remove /new_root symlink, rootfs is now mounted into /new_root, and replace it with empty directory
    rm /new_root
    mkdir -p /new_root

    if [ -e "/overlay/upper/overlayroot.resync" ]; then

      echo "overlayroot: Resyncing lower and upper ..."

      awk '$2 == "/overlay/lower" && $4 ~ /ro,/ { exit 1 }' /proc/mounts
      is_ro=$?

      if [ $is_ro -eq 1 ]; then
        mount -o rw,remount /overlay/lower
      fi

      # Delete all files which have been whited out from upper
      echo "overlayroot: Deleting all files from lower that have been wiped from upper ..."
      (cd /overlay/upper && find . -type c -print) | while read path; do
        [ "$(stat -c '%t %T' /overlay/upper/$path)" = "0 0" ] || continue
	rm -fr /overlay/lower/$path /overlay/upper/$path
      done

      # Delete all files from lower that exist in upper
      echo "overlayroot: Deleting all files from lower that exist in upper ..."
      (cd /overlay/upper && find . ! -type d -print0) | (cd /overlay/lower && xargs -0 rm -fr)

      # Copy upper to lower
      echo "overlayroot: Copying all files from upper to lower ..."
      (cd /overlay/upper && tar cf - --exclude="*/log/*" .) | (cd /overlay/lower && tar xf -)

      # Delete overlayroot.resync from lower
      rm /overlay/lower/overlayroot.resync

      # Delete all files from upper
      echo "overlayroot: Deleting all files from upper ..."
      rm -fr /overlay/upper/* /overlay/upper/.*

      # Remount 'ro' after we are finished
      if [ $is_ro -eq 1 ]; then
        mount -o ro,remount /overlay/lower
      fi
    fi

    # Build overlay FS and mount it to /new_root
    mount -t overlay overlay -o lowerdir=/overlay/lower,upperdir=/overlay/upper,workdir=/overlay/work /new_root

    # Link overlay mount into new_root, so we can work on it while the machine is running
    mkdir -p /new_root/overlay
    mount -n -o rbind /overlay /new_root/overlay
  fi;
}
