post_install() {
  echo " > Please add 'systemd' and 'sd-volatile' to your HOOKS array in /etc/mkinitcpio.conf and run mkinitcpio -P."
}

post_remove() {
  if grep -qs 'systemd.volatile' /proc/cmdline; then
    echo " > Please remove 'systemd.volatile' from your kernel commandline."
  fi
  if grep -qs 'sd-volatile' /etc/mkinitcpio.conf; then
    echo " > Please remove 'sd-volatile' from your HOOKS array in /etc/mkinitcpio.conf and run mkinitcpio -P."
  fi
}
