#!/bin/sh

sudo -v

if grep -qs '/overlay/lower' /proc/mounts; then
    sudo mount -o remount,rw /overlay/lower
fi
if grep -qs '/overlay/lower/boot' /proc/mounts; then
    sudo mount -o remount,rw /overlay/lower/boot
fi
if grep -qs '/boot' /proc/mounts; then
    sudo mount -o remount,rw /boot
fi

sudo arch-chroot /overlay/lower

echo "Leaving read-write fileystems. The filesystems remain mounted read-write until next reboot."
