#!/bin/sh

sudo -v

if ! grep -qs 'overlayroot' /proc/cmdline; then
    echo "Overlayroot not enabled. Aborting"
    exit 1
fi

mountpoints=(
    '/overlay/lower'
    '/overlay/lower/boot'
    '/boot'
)

for m in "${mountpoints[@]}"; do
    if mountpoint -q "$m"; then
        sudo mount -o remount,rw "$m"
    fi
done

sudo arch-chroot /overlay/lower

echo "Leaving read-write fileystems. The filesystems remain mounted read-write until next reboot."
