#!/bin/sh

sudo -v

mountpoints=(
    '/overlay/lower'
    '/overlay/lower/boot'
    '/boot'
)

for m in "${mountpoints[@]}"; do
    if mountpoint -q '$m'; then
        sudo mount -o remount,rw '$m'
    fi
done

sudo arch-chroot /overlay/lower

echo "Leaving read-write fileystems. The filesystems remain mounted read-write until next reboot."
